[Cu f94xbn] create main layout
Zummek/best-tournament-app pull request #12
Opened 2021-03-17 16:19 UTC by Buglik

Main layout with two tabs( tab1 and tab2 for now) and avatar button with dropdown menu (logout option and some setting that will be provided later).

2021-03-17 16:19 UTC, Zummek commented
Task linked: [CU-f94xbn Create main layout](https://app.clickup.com/t/f94xbn)

2021-03-17 21:04 UTC, Zummek reviewed
When You create/modify new view paste here screenshot

2021-03-17 21:04 UTC, Zummek commented on web-app/src/components/HeaderMenuElement.vue
> +    <q-item-section v-if="icon" class="lt-md" avatar>
Why do You want to show icon only on lower size screen than `md`?

2021-03-17 21:04 UTC, Zummek commented on web-app/src/components/HeaderMenuElement.vue
>  export default class EssentialLink extends Vue {
Change class name to this same as the file name.

2021-03-17 21:04 UTC, Zummek commented on web-app/src/components/HeaderMenuElement.vue
>    @Prop({ type: String, required: true }) readonly title!: string
`label` sounds better than `title`

2021-03-17 21:04 UTC, Zummek commented on web-app/src/layouts/MainLayout.vue
> +                <div class="row  q-pa-md">
```suggestion
                <div class="row q-pa-md">
```

2021-03-17 21:04 UTC, Zummek commented on web-app/src/layouts/MainLayout.vue
>    leftDrawerOpen = false;
It's useless variable

2021-03-17 21:04 UTC, Zummek commented on web-app/src/layouts/MainLayout.vue
> +    link: '#',
I think we can change tab titles to `News`, `Tournaments`

2021-03-18 01:38 UTC, eastemployeer requested changes
Code can be improved and simplified in several places.

2021-03-18 01:38 UTC, eastemployeer commented on web-app/src/layouts/MainLayout.vue
>          </q-toolbar-title>
```suggestion
        <q-toolbar-title :class="$q.screen.gt.xs ? 'text-center gt-xs' : ''">
          <q-icon name="emoji_events" />
          Best tournament app
        </q-toolbar-title>
```

2021-03-18 01:38 UTC, eastemployeer commented on web-app/src/layouts/MainLayout.vue
> +          <div>
Useless div

2021-03-18 01:38 UTC, eastemployeer commented on web-app/src/layouts/MainLayout.vue
> +          <HeaderMenuElement
External component for adding buttons with icons to the header? Really?

2021-03-18 10:28 UTC, Buglik commented on web-app/src/components/HeaderMenuElement.vue
> +    <q-item-section v-if="icon" class="lt-md" avatar>
that's some trash from sidebar option, removing whole HeaderMenuElement anyway

2021-03-18 10:28 UTC, Buglik commented on web-app/src/layouts/MainLayout.vue
>    leftDrawerOpen = false;
again some trash from sidebar version

2021-03-18 11:59 UTC, Zummek approved these changes
LGTM

2021-03-18 19:18 UTC, eastemployeer approved these changes

2021-03-18 19:19 UTC, merged