[Cu f9300m] Create tournament creator view
Zummek/best-tournament-app pull request #15
Opened 2021-03-26 16:17 UTC by Buglik

![Creator1view](https://user-images.githubusercontent.com/9595999/112660962-4facfa00-8e56-11eb-8ba3-b23032c0e272.png)
![Zrzut ekranu z 2021-03-27 o 17 08 19](https://user-images.githubusercontent.com/9595999/112660996-59366200-8e56-11eb-8721-f57dff81aacc.png)
![Zrzut ekranu z 2021-03-27 o 17 08 24](https://user-images.githubusercontent.com/9595999/112661000-59cef880-8e56-11eb-9ee3-a201d2980970.png)

2021-03-26 16:17 UTC, Zummek commented
Task linked: [CU-f9300m Create tournament creator view](https://app.clickup.com/t/f9300m)

2021-03-26 21:08 UTC, eastemployeer requested changes
Some of the files are very very long. Can't they be simplified? By splitting to several components or maybe other way? I am not even trying to understand this whole bunch of html

2021-03-26 21:08 UTC, eastemployeer commented on web-app/src/components/User.ts
> +}
What is it doing in this location?

2021-03-26 21:08 UTC, eastemployeer commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +    }
Almost every if/else block from this piece of code is unnecessary

2021-03-26 21:08 UTC, eastemployeer commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +    this.isErrorTeamName = false;
These names mean nothing to me

2021-03-26 21:08 UTC, eastemployeer commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +    }
WHAT IS THIS?

2021-03-26 21:08 UTC, eastemployeer commented on web-app/src/components/models.ts
> +}
And sharedTypes are for?

2021-03-26 21:08 UTC, eastemployeer commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +  private selectFilter(val: string, update: any) {
any spotted :) Change requested :)

2021-03-26 21:08 UTC, eastemployeer commented on web-app/src/components/tournament/creator/teamsList.vue
> +export default class teamsList extends Vue {
Class names begin with upper case

2021-03-26 21:41 UTC, Buglik commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +    }
148-161 checks (and reset) "team builder" form validation
164 is there to stop from submiting form when sth not right,
i've done it like this to show all wrong inputs not only the first found.

2021-03-26 21:45 UTC, Buglik commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +  private selectFilter(val: string, update: any) {
done so after consultation with @Zummek ;)

2021-03-26 21:54 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +    }
Move/Split this to `validation()` function for more readable

2021-03-26 21:56 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +  private selectFilter(val: string, update: any) {
This `update` it's crazy object is something like `(() => void) => void` but it doesn't work. Maybe need a few min to resolve this

2021-03-27 17:43 UTC, eastemployeer commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +    }
I know what this code is doing........... the problem is HOW it is doing it. Low quality code

2021-04-03 18:37 UTC, Buglik commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +  private selectFilter(val: string, update: any) {
added task in backlog at Clickup to resolve this later

2021-04-04 01:00 UTC, Zummek reviewed
So close, trifles

2021-04-04 01:00 UTC, Zummek commented on web-app/src/boot/i18n.ts
> +  // messages,
remove comments

2021-04-04 01:00 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +          :style="$q.screen.gt.xs ? '' : 'width:100%'"
If I remember correctly You can use something like this: `:style="{$q.screen.gt.xs: 'width: 100%'}"`

2021-04-04 01:00 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +                No results
locales

2021-04-04 01:00 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +                No results
locales

2021-04-04 01:00 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +  private filterOptions: User[] = [];
move class variables to top of class, variables > functions

2021-04-04 01:00 UTC, Zummek commented on web-app/src/components/tournament/creator/teamsList.vue
> +              </template> -->
```suggestion
```
Is it useless?

2021-04-04 01:00 UTC, Zummek commented on web-app/src/components/tournament/creator/teamsList.vue
> +          </q-card-section>
For something like this is dedicated component `q-card-action`
https://quasar.dev/vue-components/card#with-actions

2021-04-04 01:00 UTC, Zummek commented on web-app/src/i18n/en-us/tournament.ts
> +  teams: 'Teams List',
```suggestion
  teamList: 'Team List',
```
teams != "team list"
When you will want to use `teams` word there may be some problems

2021-04-04 01:00 UTC, Zummek commented on web-app/src/i18n/en-us/tournament.ts
> +  teamSecondMemberCreator: 'Secobd player (optional)',
Hmm maybe remove team prefix? 
When it's optional add this word to key

If you want to separate subnamespace use nested object 

```
...

team: {
   "bla": "abc",
   ...
}
...
```

You can get access to this through t("tournament.team.bla")

Capitan => Captain,
Secobd => Second

2021-04-04 01:00 UTC, Zummek commented on web-app/src/i18n/en-us/tournament.ts
> +  teamAdd: 'Add team',
```suggestion
  addTeam: 'Add team',
```
hmm, what do you think?

2021-04-04 01:00 UTC, Zummek commented on web-app/src/i18n/en-us/tournament.ts
> +  tournamentCreatorLabel: 'Tournament creator',
`label` postfix its good when You want to separate similar names ...Lable, ...Placeholder, ....Value

2021-04-04 01:00 UTC, Zummek commented on web-app/src/i18n/pl/index.ts
> +};
\n

2021-04-04 01:00 UTC, Zummek commented on web-app/src/layouts/MainLayout.vue
> +
Redundant lines

2021-04-04 01:00 UTC, Zummek commented on web-app/src/pages/Login.vue
> +      await this.$router.push({ name: 'TournamentsList' });
```suggestion
      await this.$router.push({ name: 'TournamentList' });
```

I'm not sure, that is best way to change routes. 
You definitely shouldn't use `push` only `replace`. It's silly to allow user to back to login page

2021-04-04 01:00 UTC, Zummek commented on web-app/src/pages/tournament/TournamentCreator.vue
> +          :style="$q.screen.gt.xs ? 'max-width: 300px' : ''"
try here with `:style="{...}" , but hmm i'm not sure, that is super more readable

2021-04-04 01:00 UTC, Zummek commented on web-app/src/pages/tournament/TournamentCreator.vue
> +    this.$router.push({ name: 'TournamentsList' });
Maybe push tournament Details with id of created tournament

2021-04-04 01:00 UTC, Zummek commented on web-app/src/router/index.ts
> +        name: 'login',
Hmm? Why? That was fine. Next property points to route which redirecting you after log in [something to add in future]. If you removed this, someone adds this in future task abut this feature

2021-04-04 08:41 UTC, Buglik commented on web-app/src/components/tournament/creator/teamsList.vue
> +              </template> -->
yeah, it will "disappear" :P

2021-04-04 11:12 UTC, Buglik commented on web-app/src/i18n/en-us/tournament.ts
> +  teamAdd: 'Add team',
changing to team.add (as above)

2021-04-04 11:14 UTC, Buglik commented on web-app/src/pages/tournament/TournamentCreator.vue
> +          :style="$q.screen.gt.xs ? 'max-width: 300px' : ''"
I'll leave it as it is.
For me it's way more clean.

2021-04-04 11:15 UTC, Buglik commented on web-app/src/router/index.ts
> +        name: 'login',
gonna bring it back then

2021-04-04 18:26 UTC, Zummek approved these changes
LGTM, Look to one comment below

2021-04-04 18:26 UTC, Zummek commented on web-app/src/components/tournament/creator/teamsList.vue
> +          <q-card-actions class="col-1 q-mr-lg">
are classes  required?

2021-04-04 18:26 UTC, Zummek commented on web-app/src/i18n/pl/common.ts
> +  noResults: 'Brak wyników wyszukiwania'
NoResults != NoSearchResults
So is this a search result or some other results?
This is a potential name for error because this is a common locale.

2021-04-04 18:36 UTC, Buglik commented on web-app/src/components/tournament/creator/teamsList.vue
> +          <q-card-actions class="col-1 q-mr-lg">
yeah, for display purpose

2021-04-14 16:29 UTC, Zummek reviewed
@Buglik

2021-04-14 16:29 UTC, Zummek commented on server/concepts/Tournament.ts
> +    if (!assignedTeam) throw new AppError('You are not authorized to update this match', 401);
Why did You change this? 403 is right status

2021-04-14 16:29 UTC, Zummek commented on server/controllers/authController.ts
> +  // TODO: temporary
remove com

2021-04-14 16:29 UTC, Zummek commented on server/database/repositories/TournamentRepository.ts
> +
remove

2021-04-14 16:29 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +            </q-item>
I think some optimization is needed here. Too many elements
Look to quasar doc/examples
Try to use one `q-item`, 
don't use `q-item-label` when You don't use label.

Or you may don't use `q-item` and code this with divs

2021-04-14 16:29 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +          :class="$q.screen.gt.xs ? 'col-11 q-pb-none' : 'col-12'"
```suggestion
          class="col-xs-11 col-12 q-pb-xs-none"
```
If I remember correctly, it will work

2021-04-14 16:29 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +          :disabled="players.length < 1"
```suggestion
          :disabled="!players.length"
```

2021-04-14 16:29 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +          <q-tooltip v-if="players.length < 1" content-class="bg-accent">
```suggestion
          <q-tooltip v-if="!players.length" content-class="bg-accent">
```

2021-04-14 16:29 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +    this.player = null;
If it's a temporary add-only player, can it be renamed to `tempPlayer`?

2021-04-14 16:29 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +            (user.firstName + ' ' + user.lastName)
`eslint-disable-next-line` is required? 
`@typescript-eslint/restrict-plus-operands` occurs when "When adding two variables, operands must both be of type number or of type string"
firstName and lastName should be strings hmm

2021-04-14 16:29 UTC, Zummek commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +            {{ $t('tournament.atLeastOneMemberError') }}
```suggestion
            {{ $t('tournament.team.atLeastOneMemberError') }}
```
Does this error occur only in team

2021-04-14 16:29 UTC, Zummek commented on web-app/src/components/tournament/creator/teamsList.vue
> +        {{ $t('tournament.noTeamsAddedErrorCreator') }}
Does this error occur only in team?

2021-04-14 16:29 UTC, Zummek commented on web-app/src/components/tournament/creator/teamsList.vue
> +  /* height or max-height is important */
```suggestion
```

2021-04-14 16:29 UTC, Zummek commented on web-app/src/i18n/en-us/tournament.ts
> +
remove empty line, team object move to end, it's more readable

2021-04-14 16:29 UTC, Zummek commented on web-app/src/pages/tournament/TournamentCreator.vue
> +    // console.log('Creating tournament');
```suggestion
```

2021-04-14 16:29 UTC, Zummek commented on web-app/src/pages/tournament/TournamentCreator.vue
> +  // avatarSrc: 'https://cdn.quasar.dev/img/boy-avatar.png',
```suggestion
```

2021-04-14 16:29 UTC, Zummek commented on web-app/src/services/API/apiResources/types.ts
> +export interface CreateTournamentPayload extends tournamentCreate {}
try something like `export type UpdateTournamentMatchPayload = UpdateMatchOutcomes;`

2021-04-14 16:34 UTC, Buglik commented on server/concepts/Tournament.ts
> +    if (!assignedTeam) throw new AppError('You are not authorized to update this match', 401);
That's what came with a rebase that i was actually doing with you :P

2021-04-14 16:37 UTC, Buglik commented on web-app/src/components/tournament/creator/teamBuilder.vue
> +            (user.firstName + ' ' + user.lastName)
yeah but it popped out as an error, maybe just some VS bug

2021-04-15 07:04 UTC, Zummek commented on server/concepts/Tournament.ts
> +    if (!assignedTeam) throw new AppError('You are not authorized to update this match', 401);
I only watched for correct commands. You did the rebase yourself

2021-04-15 07:06 UTC, Zummek commented on web-app/src/components/tournament/creator/teamsList.vue
> +        {{ $t('tournament.noTeamsAddedErrorCreator') }}
My point is, it can be moved to the tournament.team namespace

2021-04-22 19:36 UTC, eastemployeer approved these changes
DONE

2021-04-25 09:50 UTC, merged